In [1]:
#CAPSTONE PROJECT
#BREAST CANCER DETECTION - LOGISTIC REGRESSION

#import libraries
import numpy as np
import sklearn.datasets

#getting datasets
breast_cancer = sklearn.datasets.load_breast_cancer()

#print(breast_cancer)

X = breast_cancer.data
Y = breast_cancer.target

#print(X)
#print(Y)

print(X.shape, Y.shape)

#Import data to the pandas dataframe
import pandas as pd

data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
data['class'] = breast_cancer.target

data.head()
data.describe()

print(data['class'].value_counts())

#0 - Malignant , 1 - benign
print(breast_cancer.target_names)
data.groupby('class').mean()

#Train and Test Split 
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y)

print(Y.shape, Y_train.shape, Y_test.shape)
print(X.shape, X_train.shape, X_test.shape)

#But we do not need so many testing data, we need only 10% (0,1)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1)

print(Y.shape, Y_train.shape, Y_test.shape)
print(X.shape, X_train.shape, X_test.shape)

#Lets test if the mean of the test and train data are almost same(they should be almost equal)
print(Y.mean(), Y_train.mean(), Y_test.mean())

#Uisng stratify for correct distribution (mean) of data as the original data(Now mean is almost similar)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1, stratify=Y)
print(Y.mean(), Y_train.mean(), Y_test.mean())

#random value is used for specific splitting of data. Each value of random_state splits the data differently
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1, stratify=Y, random_state=1)

#It is not a problem if X means are different, only Y should be same 
print(X.mean(), X_train.mean(), X_test.mean())

print(X_train)

#Logistic Regression(Sigmoid function where one class falls on one side of the line, and other in the other side)
from sklearn.linear_model import LogisticRegression

#Loading the logistic regression model to variable "Classifier"
classifier = LogisticRegression()

#training the model on training data
classifier.fit(X_train, Y_train)

#Evaluation of the model
from sklearn.metrics import accuracy_score

prediction_on_training_data = classifier.predict(X_train)
accuracy_on_training_data = accuracy_score(Y_train, prediction_on_training_data)
print('Accuracy on training data', accuracy_on_training_data)

#Prediction on test data (usually less than the training data)
prediction_on_test_data = classifier.predict(X_test)
accuracy_on_test_data = accuracy_score(Y_test, prediction_on_test_data)
print('Accuracy on training data', accuracy_on_test_data)

#Detecting whether the breast cancer is benign or malignant 
input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)

#Change the input_data which is a tuple to numpy_array to make prediction
input_data_as_numpy_array = np.asarray(input_data)
print(input_data)

#reshape the array as we are predicting the output for one instance. (1,-1) is used for single instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#prediction (0 - Malign, 1- begin, it's actal value is 0)
prediction = classifier.predict(input_data_reshaped)

#Returns a list with element [0] if malign and [1] if begign
print(prediction)

if (prediction[0]==0):
    print("THE BREAST CANCER IS MALIGNANT")
else:
    print("THE BREAST CANCER IS BENIGN")

(569, 30) (569,)
1    357
0    212
Name: class, dtype: int64
['malignant' 'benign']
(569,) (426,) (143,)
(569, 30) (426, 30) (143, 30)
(569,) (512,) (57,)
(569, 30) (512, 30) (57, 30)
0.6274165202108963 0.619140625 0.7017543859649122
0.6274165202108963 0.626953125 0.631578947368421
61.890712339519624 61.31637960106119 67.04963097269005
[[1.490e+01 2.253e+01 1.021e+02 ... 2.475e-01 2.866e-01 1.155e-01]
 [1.205e+01 1.463e+01 7.804e+01 ... 6.548e-02 2.747e-01 8.301e-02]
 [1.311e+01 1.556e+01 8.721e+01 ... 1.986e-01 3.147e-01 1.405e-01]
 ...
 [1.258e+01 1.840e+01 7.983e+01 ... 8.772e-03 2.505e-01 6.431e-02]
 [1.349e+01 2.230e+01 8.691e+01 ... 1.282e-01 2.871e-01 6.917e-02]
 [1.919e+01 1.594e+01 1.263e+02 ... 1.777e-01 2.443e-01 6.251e-02]]
Accuracy on training data 0.951171875
Accuracy on training data 0.9298245614035088
(17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17

C:\Users\cig5kor\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
